### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by detiam**

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
Thanks for the update!

**Comment by korcankaraokcu** [comment]
Just checked how you handled &amp issue within other translations as well and I must say it's quite good, really well done. I'll show your work as an example for non-latin translators. Also, can you share your contact info? You mentioned that you don't use discord much so we'd need something else to communicate

**Comment by detiam** [comment]
> Just checked how you handled &amp issue within other translations as well and I must say it's quite good, really well done. I'll show your work as an example for non-latin translators. Also, can you share your contact info? You mentioned that you don't use discord much so we'd need something else to communicate

I mainly use QQ, it's 2543455938... or just @ me at github. xd
email: dehe_tian@outlook.com

**Comment by korcankaraokcu** [comment]
Thanks, will be contacting via those

**Pull request merged**
