### PR TITLE
Some things I wanted... (WIP)

### PR DESCRIPTION
**Pull request by NineBallAYAYA**
In testing it works fairly well but just in case give my code a quick skim read as im not too familier with python and might be doing something needlessly inefficient.

### CODE REVIEW

**Comment by NineBallAYAYA** [comment]
Alrighty, summery of whats in here cause the commits are becoming tad messy:
- Variable locking
- The update address table and variable locking functions run on threads seperate from the main one
- A scan progress bar cause im impatient

I cant figure out how to actually run functions in the QThread so for the time being its just running on a normal thread but it dosent block the main process anymore so it should improve performance with large tables.

**Comment by korcankaraokcu** [comment]
This PR is being discussed in our discord server, check the last pinned message for more information

**Comment by NineBallAYAYA** [comment]
AIrghty here is a list of what I did

1. Fixed the freeze stuff so it updates when the user changes the value.
2. Fixed the program not closing
3. The address table not updating when focus is lost bug dosent happen so I assume it was because of the old threading system.
4. Moved to a qt based threading system (QThreadPool)

I think everything is cool now, ping me if you have any issues with these changes.

**Comment by korcankaraokcu** [comment]
Thanks for your contribution! New features are always welcomed

**Pull request merged**
