### PR TITLE
Changed hotkeys to be global

### PR DESCRIPTION
**Pull request by ForwardFeed**
i also included the new dependency 'keyboard' in the install script.
I did this time the implementation and it worked for me.

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
While it's true that it's working, you also broke the entire hotkey system by deleting its functionality in `apply_settings`. Sorry but I cannot accept this patch as it is. It's good to see that keyboard package is working properly tho

**Comment by ForwardFeed** [comment]
Ah, the bridge confuse me,i don't know how to patch properly then. my patch is really simple it just holds in:
```py
from keyboard import add_hotkey
add_hotkey(Hotkeys.pause_hotkey.default, self.pause_hotkey_pressed)
add_hotkey(Hotkeys.break_hotkey.default, self.break_hotkey_pressed)
add_hotkey(Hotkeys.continue_hotkey.default, self.continue_hotkey_pressed)
add_hotkey(Hotkeys.toggle_attach_hotkey.default, self.toggle_attach_hotkey_pressed)
```
But i have no clue how to implement it properly then :x
because implementing alongside the QtHotkeys seems like real bad idea to me.

**Comment by korcankaraokcu** [comment]
Your patch uses static hotkeys, the original functionality let users change them as they wanted. Such implementation is not only good but also needed as users will want to see what key combination they are pressing at the time

**Comment by ForwardFeed** [comment]
My apologies, for some reason i didn't know we could change hotkey. I think i can deal with that.

**Comment by ForwardFeed** [comment]
Now global hotkeys are dynamically set. And it was working fine but it's possible some keys i haven't tried be cause of trouble.

**Comment by korcankaraokcu** [comment]
Are you sure that this patch is working? I've tested the regular F2 and F3 keys and none seems to be working at all

**Comment by ForwardFeed** [comment]
I just re cloned my fork and retried and it works, that's so awkward why does it not work?
it is the library that isn't working?
try alone this snippet of code please
```
from keyboard import add_hotkey, wait
def freeze():
	print("freeze")
add_hotkey("F2", freeze)
wait()
```

**Comment by korcankaraokcu** [comment]
Huh, it works now. Hopefully this isn't something random. Works properly right now, I'll run a few more tests to ensure its consistency. Also the patch looks quite nice, good work. I'll most likely accept this one soon

**Comment by ForwardFeed** [comment]
Okay i have found a bug while trying to understand how it couldn't have worked.
If i set a hotkey to nothing and click to validate it break the thing and i have to restart  and change the setting to make it work.

**Comment by ForwardFeed** [comment]
It's fixed

**Comment by korcankaraokcu** [comment]
Thanks for your contribution, much appreciated!

**Comment by korcankaraokcu** [comment]
Just one small note, I've increased the variable `current_settings_version` by one. If a piece of code changes how settings work, the settings version is needed to be increased by one. It resets the settings to avoid using faulty old data

**Pull request merged**
