### PR TITLE
Auto attach

### PR DESCRIPTION
**Pull request by user202729**
Allows PINCE to automatically attach to process with matching names when it's started. Useful for testing (although the popup "memory viewer" window can be annoying).

Cheat Engine has a similar feature, but it:

* Doesn't allow regex
* Can attach at all time, not just startup

It's allowed to attach to `self_pid` using this method.

-------

There is a nested for loop break at line 350, which may looks a bit confusing.

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
Fixed the QVariant bug(it's now a `str` instead of a `list`, separated with character `;`), various PEP-8 adjustments, changed `QPlainTextEdit` to `QLineEdit`(it was causing some unwanted behaviors in GUI)

Also, you should increment the settings version whenever you change the settings. It resets all the settings to make sure that users aren't forced to delete settings files whenever a patch changes the current settings. The responsible variable is `current_settings_version` in `PINCE.py`. However, this variable might be moved into a new file when the "Move GUI classes of PINCE.py to their own files" step is implemented

Here's the patch you can find all information in:https://github.com/korcankaraokcu/PINCE/commit/467a131ff6b5fbb624f7059af229cb9adea74d4d

**Comment by korcankaraokcu** [comment]
@user202729 Thanks for reporting about the self-attach, I've moved self_pid control flow to the GDB_Engine so it became impossible to attach yourself now. Here's the patch: https://github.com/korcankaraokcu/PINCE/commit/b570820e5e59e12ba0ede3a1a81f8235a0398899

**Comment by korcankaraokcu** [comment]
1. The main problem with the first design was that it was way too large for its purpose. In most use-cases, users only will need one process and they won't even enter the full name of it. It'll rarely increase to 2 or 3 processes. The weird behavior of `QPlainTextEdit` actually starts when the neighboring labels become only one line short. It looks too large compared to the neighboring labels and it requires manual size limiting. To be honest, adjusting it manually just also doesn't feel right, I felt like something was off whenever I tested it. The designer bug is the icing on the cake, it simply doesn't look fine and might confuse the future developers

2. Sounds very reasonable. But I've never encountered a process that uses the literal `;` in its name yet. It sounds like an extremely rare use-case. I think there's no need to have a downside just for the sake of this rare use-case. But you have a valid point, we must implement escaping of the literal `;` in the code. I'll do it tomorrow or this night.

3. It's not "just" an easter egg apparently. I've tried attaching to PINCE itself today and it completely froze, I had to kill it via opening another terminal and executing `kill -9`. That happens because gdb freezes the target as soon as it attaches to it. You are right about the documentation tho. I'll update the code comments asap. I don't think that QMessagebox should be updated tho, users can understand what's going on after trying a few times even if they tried to attach to PINCE by mistake

**Comment by korcankaraokcu** [comment]
Updated the self attach docstrings:https://github.com/korcankaraokcu/PINCE/commit/43f8614a2cf853d229104757b35002e3dbad16b9

**Comment by user202729** [comment]
Since you decide to stick with `;`, I suggest making the priority note explicit (because it's the only advantage `name1;name2` have over `name1|name2` (the latter use regex's native alternative feature and may be faster)).

------

Some ideas on how should the `;` feature be implemented:

1. Escape with `\`. [Turns out to be quite difficult](https://stackoverflow.com/q/18092354), because an arbitrary number of `\` before the `;` needs to be considered.
2. Use `(;)`. For example, `re.split(r'(?<!(?=\(;\)).);', data)`. Note that no regex can starts with `)`, so this is safe.

**Comment by korcankaraokcu** [comment]
Instead of tryharding to mix `;` option and regex together. I've decided to give users the ability to select if they want to use regex or not. It solves all the problems we faced here. I also updated the documentation as you requested. Here's the patch: https://github.com/korcankaraokcu/PINCE/commit/d7b1abc022ddf5afc47b890d2e8d1552bbd55944

**Pull request merged**
