### PR TITLE
Feature exit install script on error

### PR DESCRIPTION
**Pull request by Bloodiko**
Small PR

Trying to solve the "Always Showing Successful installation" issue. 

- Add Exit on Error Function
- also inofficially added SteamOS to the Switch Case 

Locally Tested with Xubuntu 20.04 with Python 3.10 in a successful run and in multiple artificially failing runs. 

(Thats my first Public PR, so i'm not sure if its correct or not. Feedback appreciated) 

Bastian

### CODE REVIEW

**Comment by brkzlr** [comment]
I'm not sure about the SteamOS case, we temporarily added it locally and tested it on a fresh SteamOS install and it still fails installation due to other requirements not being satisfied. It requires more than just adding the case to handle it like Arch.

**Comment by korcankaraokcu** [comment]
Yeah, he's unfortunately right about SteamOS, there are still missing packages and headers. You can delete that case for now

**Comment by Bloodiko** [comment]
Due to the Feedback, i've removed the SteamOS thing again.

**Comment by korcankaraokcu** [comment]
Your script fails if there's no scanmem folder. Refer to line 54

**Comment by Bloodiko** [comment]
korrect, but it shouldnt continue at this point, original script had a `exit` there. 
Because the folder is created 2 lines before - if the folder doesnt exist or the cd fails (maybe missing read or execute permission for whatever reason) - it should not continue. 

Thus its supposed to be failing there - am i wrong ?

**Comment by korcankaraokcu** [comment]
No, I mean the script does not return to `exit_on_error`, it's shown as success which defeats the main purpose of your PR. Should have worded that better, mb on that

**Comment by Bloodiko** [comment]
Yep, i did misunderstand you. Anyway, I didnt notice the artificial created context there in parenthesis. - this last commit fixed that, and for the following returns in the next few lines. 

image

**Comment by korcankaraokcu** [comment]
I've tested the `return 1` cases and apparently deleting some of them does not cause any problems. However, I think we should keep them just in case because there might be some edge cases that I'm unaware of. In conclusion, I'm merging this PR as it is

**Comment by korcankaraokcu** [comment]
I've tested the `return 1` cases and apparently deleting some of them does not cause any problems. However, I think we should keep them just in case because there might be some edge cases that I'm unaware of. In conclusion, I'm merging this PR as it is

**Comment by korcankaraokcu** [comment]
Thank you for your contribution, this QoL patch was definitely needed to remove confusion

**Pull request merged**
