### PR TITLE
Implement copy-paste entries in address table

### PR DESCRIPTION
**Pull request by user202729**
Format: List of `description, address, value_type` (identical to `read_address_table_entries` return value format)

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
Thanks for adding this feature. Adding key modifiers and copy&pasting was on my mind for a while, thanks for taking the initiative

**Comment by korcankaraokcu** [comment]
Changed your code [a bit](https://github.com/korcankaraokcu/PINCE/commit/21c303dcafdce979d59539a4b0e36b8543030abe), hope you don't mind

**Comment by user202729** [comment]
Yes, the `data` ← `records` mistake is probably because I was refactoring code in `paste_records` to `insert_records`. Thanks for the bugfix.

Probably `data` variable in `paste_records` should be renamed to `records` too, for consistency.

**Comment by korcankaraokcu** [comment]
Makes sense, it's [done](https://github.com/korcankaraokcu/PINCE/commit/e7b2f5d60565967f9ced7238c3f567c2a5ad3a55)

Btw, I want to take your opinion on the hotkeys of the context menus. MemoryViewerWindow and AddressTable uses hotkeys without key modifiers such as shift or ctrl. Does it feel better/faster to use hotkeys without key modifiers? Or is it annoying because of hitting hotkeys by mistake occasionally? Which one would you prefer, without or with key modifiers?

**Comment by user202729** [comment]
For me, either is fine.

Originally I thought about using Vim keyboard shortcuts (`d` for cut, `y` for copy, `p` for paste after, `P` for paste before), but `d` is already occupied, so I use Windows keyboard shortcut.

Also: There are currently no keyboard-only way to paste after the last entries. (with the mouse it's possible to click somewhere else and then paste, because the behavior is paste after last entry if anything selected, else paste after last)

-----

Do you think there should be more keyboard shortcuts?

**Comment by korcankaraokcu** [comment]
Yeah, I was thinking to implement one for setting data breakpoints from AddressTable. Current workflow of that process is like this:
1-)Select a row and browse memory for it
2-)Right click the first byte of the entry and choose "set data breakpoint"
3-)Choose the data breakpoint type

A shortcut that does this automatically would be nice. I originally thought of <kbd>F5</kbd>, <kbd>F6</kbd> and <kbd>F7</kbd> for each data breakpoint type. <kbd>F8</kbd>, <kbd>F9</kbd> and <kbd>F10</kbd> could also used for "what accesses/reads/writes to this address" feature.
What else do you have in mind for shortcuts?

**Pull request merged**
