### PR TITLE
Nested address table

### LINKED ISSUE #46: Nested fields in AddressTable
[enhancement].

This can be useful if multiple addressed is dependent on a common pointer.

Child fields may refer to parent's field by using an expression, `%`, for example.

Alternatively, Cheat Engine's approach is to append the child address to the parent address if it makes sense. (for example if parent address is `0x123455` and child address is `+1` then the computed address for child field is `0x123456`)

### PR DESCRIPTION
**Pull request by user202729**
Fix #46. I hope there are no bugs left.

Currently does not support editing multiple addresses at once. Also, `GuiUtils.get_current_row` only return a row if there is exactly 1 row highlighted.

Parent reference can be implemented, although it would not be useful until #45 is resolved.

Will need structured copy/paste later.

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
Thanks for the patch yet again but there are two serious problems with this patch. First one is the alteration of the `GuiUtils.get_current_row()`. That function is used in 37 different places in the project and the new version you bring breaks some of the use cases. It's designed to be used with many objects that has a selection model, such as `QTableWidget` and `QListWidget`. So it's not only limited to `QTreeWidget`. Also, you can't just delete the entire documentation of the function like that. We should discuss the necessity of the docstrings beforehand if they must be deleted. Last thing about the function is the return value. I've initially designed it to return -1 if there's no selected rows since this function is supposed to wrap `selectionModel().currentIndex().row()` and wrapped call returns -1 if there's no selected rows. If you want to change the behavior of the function, you should either write a control flow in `get_current_row` by checking the instance type of the parameter or just create another function designated for your purposes(or `QTreeWidget` in general)

The second issue is the naming of the `addressTable`. Every GUI element of PINCE is named according to the type they get initialized in. So, the proper naming convention for `addressTable` should be `treeWidget_AddressTable` instead. It makes contributing a bit easier by not forcing new developers to check ui files constantly

Thanks for your patch but I can't accept it at this state. Please do the necessary changes

**Comment by user202729** [comment]
Thanks for the comments.

* I didn't spot the `get_current_row` being applied for objects other than the table widget, so it will cause a lot of bugs, sorry for that. Will fix accordingly.
* I didn't remember deleting any docstrings. Can you point out some?
* About the naming of `addressTable` - here I don't agree that variable names should be that long. It takes a lot of time to type them out, especially without auto-completion. (the editor I uses does have auto-completion but that doesn't matter...) However because it's how it already is, I will revert it.

**Comment by user202729** [comment]
The issues above (not in the first message) should be fixed now.

However, the multiple `Fix code` commits and having both fix and rollback commits appear to be annoying. What do you think?

**Comment by user202729** [comment]
* All diff squashed.
* `-1` → `None`: Fixed.
* Multi-edit:
  * Although `exec_track_watchpoint_widget` can be called when multiple rows are selected, it operates on a single row anyway. Now it can only be called when exactly 1 row is selected.
  * Same for `browse_region_for_selected_row` and `disassemble_selected_row`.
  * Other functions (toggle, edit value, edit desc, edit address, edit type) are reverted.

**Comment by korcankaraokcu** [comment]
Fantastic work, everything works as intended. Big thanks for the patch. I might change some behaviors of the treeWidget tomorrow. I'll notify you if I do

Sorry for replying late, I had a few visitors the past week and had to sway from a hospital to another because of the military roll call procedures

**Comment by korcankaraokcu** [comment]
Fixed some trivial bugs, implemented auto-expand and deleted parameter `single` in `requires_selection`. I think that parameter is redundant because the selection behavior of address table is already the same with CE without it

@user202729 Btw, I've asked you this before but I want to ask again to confirm. Do you want me to add you in the `AUTHORS` file? Your help was significant

**Comment by user202729** [comment]
... I don't have an opinion either way. If you think you should add it, then add it.

**Comment by korcankaraokcu** [comment]
@user202729 Do you prefer the name user202729 or your real name?

**Comment by user202729** [comment]
Just use the username.

**Pull request merged**
