### PR TITLE
Adding script for possible future global hokteys

### PR DESCRIPTION
**Pull request by ForwardFeed**

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
Importing this as a separate file did not work. The loop does not catch any input.

**Comment by ForwardFeed** [comment]
It was just a script with all it need to be able to read keystrokes globally.
i haven't done any implementation yet.
The issue i have is i can't find a way to not have this function to be non thread blocking.
And i don't see myself implementing a thread for that, there might be some async way of doing this but unfortunately i don't know the python way to do it.

**Comment by korcankaraokcu** [comment]
I haven't done any implementation as well, just imported the file. From what I read, the try except loop should print something for global F2 and F3 presses right? Also, do not worry about implementation, I can do the rest if this is working consistently and conveniently

**Comment by ForwardFeed** [comment]
When you press F2/F3 it should print on the screen yes. 
If it doesn't work:
change the inside while 1 loop with print(HK.tests() only and  debug from there.
If it print's nothing when you type anything on the keyboard the issue is about the /dev/event/inputX where X a number, it's not a fixed number afaik, to find the right one there is a comment with bash command for that. (i changed it for a more accurate one, thanks stackoverflow)
If then the input show up but when you press F2 what shows up isn't 60 you have to change in hotkeys list, in the tuple with "F2" with the correct keycode (here the 60).
What i do usually is during the installation process i make the user pressing the wanted key and listen then i put it in a setting file.
If the keyboard isn't changed the keycode always remains the same.
Else i can't hardly do it myself automatically but https://pypi.org/project/evdev/ do it simply. But that would require a new dependency.

**Comment by korcankaraokcu** [comment]
That package looks quite nice, not having to bother with key maps also sound very good. Having another dependency isn't really an issue if it can be installed via pip. Thanks for sharing, good to have this as an option.

**Comment by ForwardFeed** [comment]
Well i can do a script with evedev and if it works i'll give a new PR then. 👍🏻

**Comment by korcankaraokcu** [comment]
Sure, closing this one then?

**Pull request closed without merging**
