### PR TITLE
Use system python if USE_SYSTEM_PYTHON is set

### PR DESCRIPTION
**Pull request by detiam**
For use cases like install with system package manager.

### CODE REVIEW

**Comment by brkzlr** [comment]
What will prevent users from just using this env var to bypass the installation steps? Or using possibly incompatible packages?

**Comment by detiam** [comment]
> What will prevent users from just using this env var to bypass the installation steps? Or using possibly incompatible packages?

Nothing, but if someone specifically set this env var, he should know what he's doing, right?

**Comment by detiam** [comment]
@brkzlr made some changes, now if PINCE exit with non-zero, apply venv and try again

**Comment by brkzlr** [comment]
@detiam Please wait until Korcan chips in. It's not worth losing your time implementing changes as we're not even sure if we would want this PR, or if we'd like to go the second option route (having the env var install the pip packages system-wide automatically).

**Comment by detiam** [comment]
> This would also require installation script to be modified accordingly.

Actually I do this pr is looking for a proper way to launch PINCE when PINCE and all dependencies are managed by system package manager, include python module. In this case, PINCE need to be launched from system python installation instead of venv, and dependencies will be resolved and installed by system package manager, since different distro have different situation, let installation script handle this maybe not so ideal?
Perhaps env var need to change to something like `IS_SYSTEM_PACKAGED`

> We'd also have to have a persistent flag, some kind of config file for installation.

 Maybe create an empty `.installed` file as flag after installation and verify it in `PINCE.sh` will be good? Both packager and installation script can create this easily.

>Btw, your last change makes pince restart if you quit with Ctrl+C on purpose since exit code is non-zero. Is it really necessary?

Didn't expect curl+c will cause error exit code... will revert it.

**Comment by brkzlr** [comment]
> > This would also require installation script to be modified accordingly.
> 
> 
> 
> Actually I do this pr is looking for a proper way to launch PINCE when PINCE and all dependencies are managed by system package manager, include python module. In this case, PINCE need to be launched from system python installation instead of venv, and dependencies will be resolved and installed by system package manager, since different distro have different situation, let installation script handle this maybe not so ideal?
> 
> Perhaps env var need to change to something like `IS_SYSTEM_PACKAGED`

I didn't ask this in the beginning but what would be the reason to install the packages system wide?

Users definitely shouldn't install the dependencies themselves.

I also don't see how this would help devs as venv would help with having PINCE's dependencies local instead of messing with the system.
I also personally tested our debugging scripts to make sure they're venv aware so everything is as contained as possible.

**Comment by detiam** [comment]
> > > This would also require installation script to be modified accordingly.
> > 
> > 
> > Actually I do this pr is looking for a proper way to launch PINCE when PINCE and all dependencies are managed by system package manager, include python module. In this case, PINCE need to be launched from system python installation instead of venv, and dependencies will be resolved and installed by system package manager, since different distro have different situation, let installation script handle this maybe not so ideal?
> > Perhaps env var need to change to something like `IS_SYSTEM_PACKAGED`
> 
> I didn't ask this in the beginning but what would be the reason to install the packages system wide?
> 
> Users definitely shouldn't install the dependencies themselves.
> 
> I also don't see how this would help devs as venv would help with having PINCE's dependencies local instead of messing with the system. I also personally tested our debugging scripts to make sure they're venv aware so everything is as contained as possible.
> 
> EDIT: Also, you're right about different distros having different situations and packages. That's even more of a reason to keep using venv as the packages installed there are PIP packages which are the same across all distros, instead of relying on differently named system packages.

I don't sure, use system package manager install and resolve deps just make me feel cleaner, not something must. But on other hand, there are a python installation right on my `/usr`, why don't just use it, and it will save my disk space since other app maybe use those deps too

Users don't need to install dependencies themselves, like on arch `yay -S pince-git` can install anything for you, after install just launch it from desktop launcher, out of box experience.

**Comment by detiam** [comment]
> Installing through system package manager means manual work of collecting the dependencies and then making sure to remove them if you need to uninstall PINCE, while for venv you just need to delete the PINCE folder itself and it is uninstalled.

For ArchLinux by `yay -S pince-git` user can install PINCE along with arch system package`python-distorm python-gobject python-keystone python-pyqt6 python-pexpect python-pygdbmi python-keyboard` and by `yay -Rs pince-git`, PINCE and all above packages will be removed, seems no need for manual work?

> Is this change for AUR? Is there currently a problem with the way AUR tries to install PINCE?

Yes, the original `pince-git` install `python-*` package for dependent module instead of install with pip, looks like a standard, then I follow.

> EDIT: Also about why not use the `/usr` python installation thing, the reason why we switched to VENV are the reasons we listed above, plus the fact that major distros are starting to disallow pip system package installation by default. One example is Ubuntu. You have to either create a venv for your own Python program as it is recommended by the distro and AFAIK Python community or use a flag to bypass this restriction but that's not recommended.

Wait, by system package manager I mean `pacman apt dnf`, system package referring to something like `python-*` or `python3-*`, not use pip install package to `/usr`

**Comment by brkzlr** [comment]
Can't AUR just use our installer or just copy the code that's in?

What's the issue exactly with venv that AUR is having?

**Comment by detiam** [comment]
> Can't AUR just use our installer or just copy the code that's in?
> 
> What's the issue exactly with venv that AUR is having?

Not really an issue, just if use venv this `*-git` package need to create new venv every time it updated, and other AUR packages seem to prefer using `python-*` package as deps

> Your example of manual work not being needed is for Arch only where AUR exists, but we support other distros as well.

At least AUR can do it, so why don't make it possible on AUR

**Comment by brkzlr** [comment]
Because this means adding different ways of installation just to satisfy AUR when AUR can do it a different way.

What's your take @korcankaraokcu ?

If we want this, I suggest the following:
1) Revert everything you did.
2) Add env var called `BYPASS_VENV`
3) Check this var in `PINCE.sh` so you can output this message:
"Starting in venv bypass mode. This is a mode intended for package manager installs like AUR and is not officially supported!"
4) If env var is zero, leave sh like it was before.

3 is important because we don't want to support different ways of installation, especially if it's only for one usecase, so we want to make users stumbling upon this env var aware that they shouldn't use this manually.

@detiam Please wait for Korcan's answer before you start doing work/commits. Thank you

**Comment by korcankaraokcu** [comment]
So, this is only for AUR. Considering that AUR already fixes this issue using sed, there’s no need for PINCE to handle that case specially. Having stuff like `BYPASS_VENV` or config flags will make maintaining harder. Venv part of the code most likely won't change anyway. I'll ping you on discord if it does, no worries

If venv creates issues for other distros as well, this PR could be reconsidered. It's good to have it as an idea for now, thanks for the suggestion

**Pull request closed without merging**
