### PR TITLE
Move to PyQT6

### PR DESCRIPTION
**Pull request by N00byKing**
This PR ports over the code to PyQT6.
I've tested it on my machine and it seems to work.
Additionally, I've added a convenience script to rerun .py code generation from .ui files, but I can remove it if it's unneeded.

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
This is definitely one of the biggest patches this project has seen. I'll take a look at it when I'm actively working on it again

**Comment by N00byKing** [comment]
Sure, take your time. This tool has been a great RE help!

**Comment by neoh4x0r** [comment]
I just checkedout this pr and can confirm that the switch to QT6 resolved an issue I was having where the old version would be terminated due to **recursive repaints** being detected.

**Comment by korcankaraokcu** [comment]
@neoh4x0r Thanks for the patches! You can notify me when you feel like you are done with the patches, I'll take a quick look at it when you are done. You can also take your time since a complete check will take some time, I'll just test the most critical features initially

**Comment by N00byKing** [comment]
Just saw the PR, happy to see more people interested in the PyQT6 port!

**Comment by korcankaraokcu** [comment]
@N00byKing @neoh4x0r Huge thanks for your contributions. This was the largest PR I've ever merged. I've fixed the installation script while solving the conflicts. Transition into pyqt6 was very smooth, there are only few small stuff left, I'll be hotfixing them asap

**Comment by korcankaraokcu** [comment]
Apparently there was one thing that escaped my attention: Two variables, `bHexViewScrolling` and `bDisassemblyScrolling` were created within the a py file that was automatically created by Qt Designer. Since these files were created automatically, further changes removed these variables, causing scrolling to be broken. I've moved those variables to their relevant classes in the `PINCE.py`

@neoh4x0r Hopefully this will be helpful in the future, have a nice day

**Pull request merged**
