### PR TITLE
Add zh_CN translation

### PR DESCRIPTION
**Pull request by detiam**
btw, the [AUR](https://aur.archlinux.org/packages/pince-git) package got updated

### CODE REVIEW

**Comment by brkzlr** [comment]
Is there a way we can just grab the translation files that exist inside `i18n/ts/` and run them through `compile_ts.sh` instead of having to update a `langlist` variable in there?

**Comment by detiam** [comment]
@brkzlr updated

**Comment by brkzlr** [comment]
Looks good, thank you!

**Comment by korcankaraokcu** [comment]
It works pretty well. Thank you for extending the ts script functionality, it was a much needed feature. Also thanks @brkzlr for his excellent suggestion

**Comment by korcankaraokcu** [comment]
Just one issue, pince scripts are usually POSIX compatible. I've fixed it myself tho, no worries. Just saying for future reference

https://github.com/korcankaraokcu/PINCE/commit/a1abc9c5da4c155dc22b1c2ec5aaf25cd6ad701d

**Pull request merged**
