### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by detiam**
btw why the OK and Cancel button are unable to translate?

image

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
A very good question. They are set with `QDialogButtonBox.StandardButton`. I'll try to find a solution for this. Thanks for making the Chinese translation up to date

**Comment by korcankaraokcu** [comment]
With https://github.com/korcankaraokcu/PINCE/commit/7869362f4d4144ad2a6b6d25696f405aea75e211, this issue should be fixed now, test for yourself

**Comment by detiam** [comment]
> With 7869362f4d4144ad2a6b6d25696f405aea75e211, this issue should be fixed now, test for yourself

@korcankaraokcu I updated the translation strings by f21e0e623d6fefdf776ee4dc2056210becf75f8f and run, the OK and Cancel button translated.
But the strings with `&amp`  are not translated, like:
Open file.

**Comment by korcankaraokcu** [comment]
`QT_TRANSLATE_NOOP("QPlatformTheme", "&Open")`

It's handled like above, is there something wrong with it? Btw, I'm going thru flu right now. I'll investigate this thoroughly once I recover

**Comment by korcankaraokcu** [comment]
I'm back and confirmed this issue on my end now. We can continue from #222 for possible fixes

**Pull request merged**
