### PR TITLE
Make the address table items store the original address expression

### LINKED ISSUE #45: Should PINCE simplify address?
Currently, if a complex evaluate-able expression (such as `*(void**)0x123456`) is entered as the address, it's converted into the evaluated value. While pointer is not available, this has the equivalent functionality.

(line 789~790 of `PINCE.py` do the conversion)

This is not useful if cheat tables can be saved/loaded (as the resulting address may change, while the base pointer usually doesn't)

So what should be done?

* Implement proper pointer type, and don't use this approach
* Remove the behavior, and use `*(void**)` instead of pointer

### PR DESCRIPTION
**Pull request by user202729**
Fixes #45.

Changes:

* Since the address table items store `address_expr`, `address_expr` needs to be passed into `change_address_table_entries`.
* So, calling convention (parameters) of `change_address_table_entries` is changed, and all of its occurences needs to be modified accordingly. That is a big change and I hope there is no bug.
* There are some redundant `text_to_valuetype` and `valuetype_to_text` calls. To solve it, it's necessary to refactor the code to store the details inside the items ("text_to_valuetype is a bad design pattern. Store the information inside the items of tableWidget_AddressTable instead" inside roadmap)

### CODE REVIEW

**Comment by korcankaraokcu** [comment]
But the others(`description` and `typeofaddress`) are still column values. I don't think it's that confusing. In fact, the function itself is quite self-explanatory, you can even delete that docstring at this point. You are free to do whatever you want with it. Btw, do you get the notification without me mentioning you? Asking because this PR is already closed

**Comment by korcankaraokcu** [comment]
Assuming that you didn't @user202729. I guess we really need to mention each other after a PR gets closed

**Comment by user202729** [comment]
... I forgot to update `update_address_table_manually`. Now `address` won't change when the address expression evaluates to a different value.

There are 2 options.

1. Updates the address one-by-one with `convert_symbol_to_address`. However I think that doing multiple `send_command` has some performance impact.
2. Make a new command to convert multiple symbols to addresses.

**Comment by korcankaraokcu** [comment]
Actually PINCE is using shared memory for IPC for a while now. Updated the #6 accordingly. The performance shouldn't be a huge issue. I'm planning to implement a solution that uses thread injection in gdb for this

**Comment by user202729** [comment]
Info: I tried using multiple calls to `GDB_Engine.convert_symbol_to_address` to implement `update_address_table_manually` at https://github.com/user202729/PINCE/commit/b746606730a3b94129673cabd46f681bcf9d9737. For about 100 addresses, the `pince-read-multiple-addresses` takes about `0.003` seconds while loading the addresses takes about `0.2` seconds, that's about 100 orders of magnitude slower.

**Comment by korcankaraokcu** [comment]
@user202729 Working on this issue now. Will benchmark both of the options. Btw, do you think that using a tree model instead of a tree widget has a better impact on the performance on this case?

**Comment by user202729** [comment]
I implemented option (1) https://github.com/user202729/PINCE/commit/8391e3d086581962b02440d91853122452e17eef and another alternative which executes multiple commands while calling `send_command` only once https://github.com/user202729/PINCE/commit/3f5e264e76e499e69315195e73260bc91a004f5a . The latter option is 7 times faster on my machine (assume gdb output is muted and debug info is not printed, and there are 100 records)

I didn't try implementing custom pince extension command.

-------

A tree model has the (only, that I can think of) advantage that the whole information doesn't need to be refreshed at once. Doesn't have much to do with this particular case; but in general it should improve performance if there are a lot of entries.

**Comment by korcankaraokcu** [comment]
That was really quick, I was just going to finish a new test branch, you ninja'd me :smile: Usage of the extension commands makes the real optimization difference. With extension commands, you can carry a piece of code/function inside gdb and call it as an internal command. With that, you evade calling the same command multiple times like you did with your 2nd solution. How about a distribution of work? Meanwhile I work on this extension command, could you try benchmarking between model and widget for 10000 entries?

**Comment by korcankaraokcu** [comment]
`pince-read-multiple-addresses` works quite fast, it processes 10000 different entries in 0.03-0.04 secs but `pince-multiple-symbols-to-addresses` doesn't work that fast unfortunately, it processes the same amount of entries in 0.33-0.35 secs. The performance difference is huge, so it's impossible to convert symbols for every entry, conversion should be used only if the target is confirmed for being a symbol. We must find an elegant way to differentiate between an address and a symbol
Created a new branch for the new patch btw, didn't want to merge it before taking your opinions. [Feel free to PR](https://github.com/korcankaraokcu/PINCE/compare/update_address_table_manually_fix)

**Comment by user202729** [comment]
The patch looks fine. However it would be better if the commit is splitted into one about PEP-8 fix and another about the functional fix, so I don't have to look at the PEP-8 fix while seeing the difference. Like [this](https://github.com/user202729/PINCE/commits/update_address_table_manually_fix) (not sure if you intended to add the debug feature).

------

That's because the command actually evaluates arbitrary C expression, and it has a reasonable overhead. To filter some trivially-evaluate-able entries, I think it's possible to use `int(x)`, `int(x, 16)` or even `ast.literal_eval(x)` (that one also supports `+` and `-`).

**Comment by korcankaraokcu** [comment]
1. You are completely right, separated the commits as you suggested. Also that debug feature wasn't intended, I just forgot to remove it before pushing. I don't know what was going thru my mind, shouldn't have committed at 4am :smile: Glad that I created a separate branch instead of pushing that monstrosity directly to the master
2. Benchmarked `int(x, 16)` against `ast.literal_eval(x)` and even being within a `try/except` block, int conversion was 6 times faster than the `ast.literal_eval(x)`, so using that for optimization. I'm considering where to implement the optimization right now. I might even refactor the conversion functions
3. You are right, I'll extend the `gdb_output_mode` feature

**Comment by user202729** [comment]
Using `int(x, 16)` would change the behavior -- for example, `10` would evaluate to address `0x00000010`, not `0x0000000A`. I suggest `int(x, 0)`.

**Comment by korcankaraokcu** [comment]
Updated the `gdb_output_mode`: https://github.com/korcankaraokcu/PINCE/commit/54382eb64e04b074a6aceb84a5ba9eb2e8c098ff

**Pull request merged**
